"""
Naija Pocket Business Center
ADA RESPONSE ENGINE

INTELLIGENCE-FIRST DOCUMENT ENGINE
==================================

Ada is responsible for:
    - understanding the customer's request
    - understanding the selected service
    - deciding what information is needed
    - generating complete work
    - reviewing the complete work
    - applying customer corrections

The application is responsible for:
    - storing the current document
    - storing document versions
    - page order
    - review state
    - approval
    - payment
    - delivery

IMPORTANT
---------

A service does NOT automatically require a page count.

Examples:

    Seminar Paper
        → may require desired length

    CV
        → does not require a page count

    Letterhead
        → does not require a page count

    Cover Letter
        → does not require a page count

Ada determines what information is relevant from the
selected service and the customer's actual request.

DOCUMENT RULE
-------------

The document generated by Ada is treated as ONE COMPLETE
DOCUMENT.

It must never be replaced by:

    - a summary
    - a review response
    - a partial Groq response
    - a single chunk
    - a page preview

The application receives:

    document_text
    pages
    total_pages

before the review screen is allowed to operate.

LONG DOCUMENT RULE
------------------

A large document may require multiple intelligence requests.

Those requests are internal.

They must NEVER become separate documents.

Generation therefore uses continuation when necessary:

    PART 1
       ↓
    PART 2
       ↓
    PART 3
       ↓
      ...
       ↓
    COMPLETE DOCUMENT
       ↓
    PAGE COLLECTION
       ↓
    REVIEW

No generated part is presented to the customer as the
complete document until generation has finished.

"""

from __future__ import annotations

import os
import re
import traceback
from typing import Any, Callable

try:
    from groq import Groq
except ImportError:
    Groq = None

from ada_prompt_manager import AdaPromptManager
from billing_manager import BillingManager


# ============================================================
# CONFIGURATION
# ============================================================

DEFAULT_MODEL = "openai/gpt-oss-20b"

MODEL = (
    os.getenv("GROQ_MODEL")
    or DEFAULT_MODEL
).strip()

API_KEY = (
    os.getenv("GROQ_API_KEY")
    or os.getenv("GROQ_APIKEY")
    or ""
).strip()

EXPOSE_ERRORS_TO_CLIENT = (
    os.getenv(
        "ADA_EXPOSE_ERRORS",
        "false",
    )
    .strip()
    .lower()
    in {
        "1",
        "true",
        "yes",
        "on",
    }
)


# ============================================================
# LIMITS
# ============================================================

MAX_SYSTEM_PROMPT_CHARS = 14000

MAX_HISTORY_MESSAGES = 10
MAX_HISTORY_MESSAGE_CHARS = 2500

MAX_USER_MESSAGE_CHARS = 8000
MAX_CONTEXT_CHARS = 7000

MAX_DOCUMENT_PAGES = 1000

# Generation is continuation-based.
# This is a request size, NOT a document size.
GENERATION_REQUEST_CHARS = 9000
GENERATION_OUTPUT_TOKENS = 3500

MAX_GENERATION_PARTS = 40

# Review
REVIEW_REQUEST_CHARS = 8500
REVIEW_OUTPUT_TOKENS = 1200

# Correction
CORRECTION_REQUEST_CHARS = 8500
CORRECTION_OUTPUT_TOKENS = 3000

# Page construction
DEFAULT_PAGE_CHARS = 7000


# ============================================================
# EVENTS
# ============================================================

REVIEW_EVENTS = {
    "review",
    "review_requested",
    "review_called",
    "open_review",
    "review_page",
    "review_document",
    "send_for_review",
    "send_review",
}

CORRECTION_EVENTS = {
    "review_correction",
    "document_correction",
    "revise_work",
    "correction",
}


# ============================================================
# ERROR
# ============================================================

class AdaResponseError(Exception):

    def __init__(
        self,
        message: str,
        *,
        stage: str,
        category: str = "APPLICATION",
        status_code: int | None = None,
        original: Exception | None = None,
    ):
        super().__init__(message)

        self.stage = stage
        self.category = category
        self.status_code = status_code
        self.original = original


# ============================================================
# GROQ
# ============================================================

_client = None


def get_client():

    global _client

    if _client is not None:
        return _client

    if Groq is None:
        raise AdaResponseError(
            "The groq package is not installed.",
            stage="CLIENT_INITIALIZATION",
            category="CONFIGURATION",
        )

    if not API_KEY:
        raise AdaResponseError(
            "GROQ_API_KEY is missing.",
            stage="CLIENT_INITIALIZATION",
            category="CONFIGURATION",
        )

    try:

        _client = Groq(
            api_key=API_KEY
        )

        return _client

    except Exception as error:

        raise AdaResponseError(
            "Groq client initialization failed.",
            stage="CLIENT_INITIALIZATION",
            category="GROQ_CLIENT",
            original=error,
        ) from error


def get_ada_model() -> str:
    return MODEL


def is_configured() -> bool:

    return (
        Groq is not None
        and bool(API_KEY)
    )


# ============================================================
# TEXT
# ============================================================

def safe_text(value: Any) -> str:

    if value is None:
        return ""

    if isinstance(value, str):
        return value.strip()

    return str(value).strip()


def compact_text(
    value: Any,
    maximum: int,
) -> str:

    text = safe_text(value)

    if not text:
        return ""

    if len(text) <= maximum:
        return text

    if maximum < 100:
        return text[:maximum]

    marker = (
        "\n\n"
        "[INTERNAL CONTEXT COMPACTED]\n\n"
    )

    available = maximum - len(marker)

    if available <= 0:
        return text[:maximum]

    first = int(
        available * 0.65
    )

    last = available - first

    return (
        text[:first]
        + marker
        + text[-last:]
    )


def split_for_intelligence(
    text: str,
    maximum: int,
) -> list[str]:
    """
    Internal splitting only.

    The returned parts are never treated as separate documents.
    """

    text = safe_text(text)

    if not text:
        return []

    if len(text) <= maximum:
        return [text]

    parts = []

    start = 0
    length = len(text)

    while start < length:

        if length - start <= maximum:
            parts.append(
                text[start:].strip()
            )
            break

        end = start + maximum
        window = text[start:end]

        positions = [
            window.rfind("\n\n"),
            window.rfind("\n"),
            window.rfind(". "),
            window.rfind("? "),
            window.rfind("! "),
            window.rfind(" "),
        ]

        usable = [
            position
            for position in positions
            if position >= int(maximum * 0.55)
        ]

        if usable:
            boundary = max(usable)
        else:
            boundary = maximum

        part = text[
            start:start + boundary
        ].strip()

        if part:
            parts.append(part)

        next_start = start + boundary

        if next_start <= start:
            next_start = end

        start = next_start

    return parts


# ============================================================
# ERROR LOGGING
# ============================================================

def classify_error(error: Exception) -> str:

    status = getattr(
        error,
        "status_code",
        None,
    )

    message = safe_text(
        error
    ).lower()

    if status == 429:
        return "GROQ_RATE_LIMIT"

    if status == 401:
        return "GROQ_AUTHENTICATION"

    if status == 403:
        return "GROQ_PERMISSION"

    if status == 404:
        return "GROQ_NOT_FOUND"

    if status == 400:
        return "GROQ_BAD_REQUEST"

    if status == 413:
        return "GROQ_REQUEST_TOO_LARGE"

    if status and status >= 500:
        return "GROQ_SERVER_ERROR"

    if "timeout" in message:
        return "NETWORK"

    if "connection" in message:
        return "NETWORK"

    return "GROQ_REQUEST_ERROR"


def log_error(
    title: str,
    error: Exception,
    *,
    stage: str,
):

    print()
    print("=" * 78)
    print("ADA ERROR:", title)
    print("=" * 78)
    print("Stage:", stage)
    print("Category:", classify_error(error))
    print("Model:", MODEL)
    print("API key configured:", bool(API_KEY))
    print("Error:", compact_text(error, 1500))
    traceback.print_exc()
    print("=" * 78)
    print()


def client_error_message(
    error: Exception,
) -> str:

    if not EXPOSE_ERRORS_TO_CLIENT:

        return (
            "I could not process your request right now. "
            "Please try again."
        )

    return (
        "Technical error detected.\n\n"
        f"Category: {classify_error(error)}\n"
        f"Error: {compact_text(error, 1200)}"
    )


# ============================================================
# SERVICE
# ============================================================

class AdaResponse:

    def __init__(
        self,
        service: str | None = None,
    ):

        self.service = safe_text(
            service
        ) or None

        self.prompt_manager = (
            AdaPromptManager()
        )

        self.billing = (
            BillingManager()
        )

        self.history: list[
            dict[str, str]
        ] = []

    # ========================================================
    # SERVICE
    # ========================================================

    def set_service(
        self,
        service: str | None,
    ):

        service = safe_text(
            service
        )

        if service:
            self.service = service

    def normalize_service(
        self,
        service: str | None,
    ) -> str | None:

        service = safe_text(
            service
        )

        if not service:
            return self.service

        try:

            normalized = (
                self.billing
                .normalize_service(
                    service
                )
            )

            return (
                safe_text(
                    normalized
                )
                or service
            )

        except Exception as error:

            log_error(
                "SERVICE NORMALIZATION FAILED",
                error,
                stage="SERVICE_NORMALIZATION",
            )

            return service

    # ========================================================
    # BILLING
    # ========================================================

    def get_billing_context(
        self,
        service: str | None,
    ) -> str:

        service = self.normalize_service(
            service
        )

        if not service:
            return ""

        try:

            item = (
                self.billing
                .get_service(
                    service
                )
            )

        except Exception as error:

            log_error(
                "BILLING LOOKUP FAILED",
                error,
                stage="BILLING_LOOKUP",
            )

            return (
                "OFFICIAL BILLING FACTS\n"
                "Billing information unavailable.\n"
                "Do not invent pricing."
            )

        if not item:

            return (
                "OFFICIAL BILLING FACTS\n"
                "No billing record found.\n"
                "Do not invent pricing."
            )

        price = item.get(
            "price",
            0,
        )

        billing_type = item.get(
            "billing"
        )

        if billing_type == "fixed":

            pricing = (
                f"Official price: ₦{price:,}\n"
                "Billing type: fixed"
            )

        elif billing_type == "per_page":

            pricing = (
                f"Official price: ₦{price:,} per page\n"
                "Billing type: per_page"
            )

        elif billing_type == "quotation":

            pricing = (
                "Official price: quotation required\n"
                "Billing type: quotation"
            )

        else:

            pricing = (
                f"Official price: ₦{price:,}\n"
                f"Billing type: {billing_type}"
            )

        return (
            "OFFICIAL BILLING FACTS\n"
            f"Service: {service}\n"
            f"{pricing}\n"
            "BillingManager is authoritative."
        )

    # ========================================================
    # CORE INTELLIGENCE
    # ========================================================

    def intelligence_rules(self) -> str:

        return """
You are Ada, the intelligent customer-facing assistant
of Naija Pocket Business Center.

You are not a keyword-matching bot.

Understand the customer's meaning, request, selected service,
provided information and current application state.

SERVICE INTELLIGENCE
--------------------

Do not assume every service has the same information requirements.

Determine what information is genuinely relevant to the
selected service.

A page count is NOT globally required.

For example:

- A seminar paper may require desired length.
- A CV may require education, experience, skills and contact
  information.
- A letterhead may require business name, contact details and
  design information.
- A cover letter may require job and applicant information.
- Other services have their own requirements.

Ask only for information that is actually necessary.

DOCUMENT GENERATION
-------------------

When the customer has supplied enough information to complete
the requested service, produce the complete requested work.

Do not deliberately produce an introduction and stop.

Do not claim that a document is complete when only part of it
has been written.

If the requested document is long, continue working until the
requested document has reached a natural conclusion.

Do not invent a page count.

Do not add a page count unless the customer requested one or
the service genuinely requires one.

DOCUMENT PRESERVATION
---------------------

A document is one complete work.

Internal intelligence requests are not separate documents.

Never replace a document with:

- a summary
- a review
- an excerpt
- a single generation part
- a page preview

REVIEW
------

Review the actual complete document.

Do not confuse review findings with document content.

CORRECTIONS
-----------

Use the current document supplied by the application.

Apply the customer's requested correction.

Preserve unrelated content.

Never revert to an older document.

Never silently remove useful content.

FACTS
-----

Do not invent customer facts.

Do not fabricate references, qualifications, employment history,
addresses, dates or other personal information.

If information is required and genuinely missing, ask for it.

COMMUNICATION
-------------

Speak naturally and warmly.

Never expose internal architecture.

Never mention Groq, APIs, token limits, prompts or internal
processing.
"""

    # ========================================================
    # SYSTEM PROMPT
    # ========================================================

    def build_system_prompt(
        self,
        *,
        service: str | None = None,
        context: str | None = None,
    ) -> str:

        active_service = (
            self.normalize_service(
                service
            )
        )

        parts = []

        try:

            prompt = (
                self.prompt_manager
                .build_prompt(
                    service=active_service
                )
            )

            if prompt:
                parts.append(
                    compact_text(
                        prompt,
                        8000,
                    )
                )

        except Exception as error:

            log_error(
                "PROMPT MANAGER FAILED",
                error,
                stage="PROMPT_MANAGER",
            )

        parts.append(
            self.intelligence_rules()
        )

        billing = (
            self.get_billing_context(
                active_service
            )
        )

        if billing:
            parts.append(
                billing
            )

        if active_service:

            parts.append(
                "SELECTED SERVICE\n"
                + active_service
            )

        if context:

            parts.append(
                "CURRENT APPLICATION STATE\n"
                + compact_text(
                    context,
                    MAX_CONTEXT_CHARS,
                )
            )

        return compact_text(
            "\n\n".join(parts),
            MAX_SYSTEM_PROMPT_CHARS,
        )

    # ========================================================
    # HISTORY
    # ========================================================

    def add_history(
        self,
        role: str,
        content: str,
    ):

        role = safe_text(
            role
        )

        content = safe_text(
            content
        )

        if not role or not content:
            return

        self.history.append(
            {
                "role": role,
                "content": content,
            }
        )

        self.history = (
            self.history[
                -MAX_HISTORY_MESSAGES:
            ]
        )

    def clear_history(self):

        self.history.clear()

    # ========================================================
    # GROQ
    # ========================================================

    def call_groq(
        self,
        *,
        messages: list[dict[str, str]],
        output_tokens: int,
        stage: str,
        event: str | None = None,
    ) -> str:

        client = get_client()

        print()
        print("=" * 78)
        print("ADA INTELLIGENCE")
        print("=" * 78)
        print("Stage:", stage)
        print("Model:", MODEL)
        print("Messages:", len(messages))
        print("Output tokens:", output_tokens)

        if event:
            print("Event:", event)

        print("=" * 78)

        try:

            response = (
                client
                .chat
                .completions
                .create(
                    model=MODEL,
                    messages=messages,
                    temperature=0.2,
                    max_completion_tokens=(
                        output_tokens
                    ),
                )
            )

        except Exception as error:

            log_error(
                "INTELLIGENCE REQUEST FAILED",
                error,
                stage=stage,
            )

            raise AdaResponseError(
                str(error),
                stage=stage,
                category=classify_error(error),
                status_code=getattr(
                    error,
                    "status_code",
                    None,
                ),
                original=error,
            ) from error

        if not response:
            raise AdaResponseError(
                "No intelligence response returned.",
                stage=stage,
                category="EMPTY_RESPONSE",
            )

        if not response.choices:
            raise AdaResponseError(
                "No intelligence choice returned.",
                stage=stage,
                category="EMPTY_RESPONSE",
            )

        content = safe_text(
            response
            .choices[0]
            .message
            .content
        )

        if not content:

            raise AdaResponseError(
                "Intelligence returned empty content.",
                stage=stage,
                category="EMPTY_RESPONSE",
            )

        print(
            "Ada intelligence response received."
        )

        return content

    # ========================================================
    # GENERATION PROMPT
    # ========================================================

    def build_generation_prompt(
        self,
        *,
        service: str,
        customer_request: str,
        supplied_material: str = "",
        previous_document: str = "",
        continuation: bool = False,
    ) -> str:

        if continuation:

            instruction = """
Continue the document from exactly where the existing
document ends.

The previous material is part of the SAME document.

Do not restart the document.

Do not repeat sections already written.

Do not summarize what has already been written.

Continue until the requested work reaches a natural conclusion.

Return only the continuation of the document.
"""

        else:

            instruction = """
Create the complete requested document.

Do not stop after an introduction or partial section.

Follow the requested structure and produce the work through
its natural conclusion.

Return the document itself, not an explanation of what you
would write.
"""

        return (
            "DOCUMENT GENERATION\n\n"
            f"SERVICE:\n{service}\n\n"
            "CUSTOMER REQUEST:\n"
            f"{compact_text(customer_request, 6000)}\n\n"
            "SUPPLIED MATERIAL:\n"
            f"{compact_text(supplied_material, 7000)}\n\n"
            "CURRENT DOCUMENT MATERIAL:\n"
            f"{compact_text(previous_document, 7000)}\n\n"
            + instruction
            + "\nDo not invent customer-specific facts."
        )

    # ========================================================
    # COMPLETE DOCUMENT GENERATION
    # ========================================================

    def generate_document(
        self,
        *,
        service: str | None,
        customer_request: str,
        supplied_material: str = "",
        context: str | None = None,
        progress_callback: Callable[
            [dict[str, Any]],
            None
        ] | None = None,
    ) -> dict[str, Any]:
        """
        Generate a complete document.

        This method is deliberately separate from review.

        It does not return the first Groq response and call that
        the finished document.

        It continues until Ada determines that the requested
        work has reached its natural conclusion.
        """

        active_service = (
            self.normalize_service(
                service
            )
            or safe_text(service)
            or self.service
            or "General Business Center Service"
        )

        customer_request = safe_text(
            customer_request
        )

        supplied_material = safe_text(
            supplied_material
        )

        if not customer_request:

            raise AdaResponseError(
                "No customer request was supplied.",
                stage="GENERATION_INTAKE",
                category="EMPTY_REQUEST",
            )

        system_prompt = (
            self.build_system_prompt(
                service=active_service,
                context=context,
            )
        )

        document_parts = []

        for part_number in range(
            1,
            MAX_GENERATION_PARTS + 1,
        ):

            current_document = "\n\n".join(
                document_parts
            ).strip()

            prompt = (
                self.build_generation_prompt(
                    service=active_service,
                    customer_request=customer_request,
                    supplied_material=supplied_material,
                    previous_document=current_document,
                    continuation=bool(
                        document_parts
                    ),
                )
            )

            messages = [
                {
                    "role":
                        "system",
                    "content":
                        system_prompt,
                },
                {
                    "role":
                        "user",
                    "content":
                        prompt,
                },
            ]

            generated = self.call_groq(
                messages=messages,
                output_tokens=GENERATION_OUTPUT_TOKENS,
                stage="DOCUMENT_GENERATION",
            )

            generated = safe_text(
                generated
            )

            if not generated:
                break

            document_parts.append(
                generated
            )

            current_document = "\n\n".join(
                document_parts
            ).strip()

            if progress_callback:

                progress_callback(
                    {
                        "type":
                            "generation_progress",

                        "part":
                            part_number,

                        "status":
                            "writing",

                        "content_length":
                            len(current_document),
                    }
                )

            # ------------------------------------------------
            # Ask intelligence whether the document is actually
            # finished.
            # ------------------------------------------------

            completion_prompt = (
                "DOCUMENT COMPLETION CHECK\n\n"
                "Determine whether the document below has "
                "reached a natural and complete conclusion "
                "for the customer's request.\n\n"
                "CUSTOMER REQUEST:\n"
                f"{compact_text(customer_request, 5000)}\n\n"
                "DOCUMENT:\n"
                f"{compact_text(current_document, 9000)}\n\n"
                "Return exactly one word:\n"
                "COMPLETE\n"
                "or\n"
                "CONTINUE"
            )

            check = self.call_groq(
                messages=[
                    {
                        "role":
                            "system",
                        "content":
                            system_prompt,
                    },
                    {
                        "role":
                            "user",
                        "content":
                            completion_prompt,
                    },
                ],
                output_tokens=20,
                stage="DOCUMENT_COMPLETION_CHECK",
            )

            decision = safe_text(
                check
            ).upper()

            if "COMPLETE" in decision:
                break

        else:

            raise AdaResponseError(
                (
                    "Document generation did not reach "
                    "a safe completion point."
                ),
                stage="DOCUMENT_GENERATION",
                category="GENERATION_INCOMPLETE",
            )

        document_text = "\n\n".join(
            document_parts
        ).strip()

        if not document_text:

            raise AdaResponseError(
                "No document content was generated.",
                stage="DOCUMENT_GENERATION",
                category="EMPTY_DOCUMENT",
            )

        pages = self.document_to_pages(
            document_text
        )

        result = {
            "type":
                "document_completed",

            "status":
                "completed",

            "service":
                active_service,

            "document_text":
                document_text,

            "pages":
                pages,

            "total_pages":
                len(pages),
        }

        if progress_callback:

            progress_callback(
                result
            )

        return result

    # ========================================================
    # DOCUMENT → PAGES
    # ========================================================

    @staticmethod
    def document_to_pages(
        document_text: str,
    ) -> list[dict[str, Any]]:
        """
        Convert the COMPLETE document into application pages.

        Page construction happens AFTER generation.

        This means the review system cannot accidentally receive
        the first generation response as the entire document.
        """

        document_text = safe_text(
            document_text
        )

        if not document_text:
            return []

        # ----------------------------------------------------
        # Respect explicit page markers if present.
        # ----------------------------------------------------

        pattern = re.compile(
            r"(?:^|\n)"
            r"(?:={2,}\s*)?"
            r"PAGE\s+(\d+)"
            r"(?:\s*={2,})?"
            r"\s*(?:\n|$)",
            re.IGNORECASE,
        )

        matches = list(
            pattern.finditer(
                document_text
            )
        )

        if matches:

            pages = []

            for index, match in enumerate(
                matches
            ):

                start = match.end()

                if index + 1 < len(matches):
                    end = matches[
                        index + 1
                    ].start()
                else:
                    end = len(
                        document_text
                    )

                content = document_text[
                    start:end
                ].strip()

                if content:

                    pages.append(
                        {
                            "page_number":
                                int(
                                    match.group(1)
                                ),

                            "content":
                                content,

                            "status":
                                "ready",
                        }
                    )

            if pages:
                return pages

        # ----------------------------------------------------
        # No explicit pages:
        # construct logical pages without losing content.
        # ----------------------------------------------------

        parts = split_for_intelligence(
            document_text,
            DEFAULT_PAGE_CHARS,
        )

        return [
            {
                "page_number":
                    index,

                "content":
                    part,

                "status":
                    "ready",
            }
            for index, part in enumerate(
                parts,
                start=1,
            )
            if part
        ]

    # ========================================================
    # NORMALIZE EXISTING PAGES
    # ========================================================

    @staticmethod
    def normalize_document_pages(
        pages: Any,
    ) -> list[dict[str, Any]]:

        if pages is None:
            return []

        if isinstance(
            pages,
            str,
        ):

            return AdaResponse.document_to_pages(
                pages
            )

        if not isinstance(
            pages,
            list,
        ):

            pages = [pages]

        result = []

        for index, item in enumerate(
            pages,
            start=1,
        ):

            if isinstance(
                item,
                str,
            ):

                content = safe_text(
                    item
                )

                if content:

                    result.append(
                        {
                            "page_number":
                                index,

                            "content":
                                content,

                            "status":
                                "ready",
                        }
                    )

                continue

            if isinstance(
                item,
                dict,
            ):

                content = safe_text(
                    item.get("content")
                    or item.get("text")
                    or item.get("page_content")
                    or item.get("document_text")
                )

                if not content:
                    continue

                try:

                    page_number = int(
                        item.get(
                            "page_number",
                            index,
                        )
                    )

                except Exception:

                    page_number = index

                result.append(
                    {
                        "page_number":
                            page_number,

                        "content":
                            content,

                        "status":
                            item.get(
                                "status",
                                "ready",
                            ),
                    }
                )

        return sorted(
            result,
            key=lambda item: int(
                item["page_number"]
            ),
        )

    # ========================================================
    # REVIEW
    # ========================================================

    def review_document_pages(
        self,
        *,
        pages: list[Any],
        service: str | None = None,
        context: str | None = None,
        customer_request: str = "",
        event: str = "review",
        progress_callback: Callable[
            [dict[str, Any]],
            None
        ] | None = None,
    ) -> dict[str, Any]:
        """
        Review the COMPLETE current document.

        The original page content is never replaced by the
        review response.
        """

        normalized = (
            self.normalize_document_pages(
                pages
            )
        )

        if not normalized:

            raise AdaResponseError(
                "No complete document was supplied for review.",
                stage="REVIEW_INTAKE",
                category="EMPTY_DOCUMENT",
            )

        total_pages = len(
            normalized
        )

        page_results = []

        complete_document = self.assemble_document(
            normalized
        )

        system_prompt = (
            self.build_system_prompt(
                service=service,
                context=context,
            )
        )

        for position, page in enumerate(
            normalized,
            start=1,
        ):

            page_number = page[
                "page_number"
            ]

            content = page[
                "content"
            ]

            if progress_callback:

                progress_callback(
                    {
                        "type":
                            "page_started",

                        "page_number":
                            page_number,

                        "position":
                            position,

                        "total_pages":
                            total_pages,

                        "content":
                            content,

                        "status":
                            "processing",
                    }
                )

            # ------------------------------------------------
            # Review the page with document-level context.
            # ------------------------------------------------

            prompt = (
                "DOCUMENT REVIEW\n\n"
                f"SERVICE:\n"
                f"{safe_text(service)}\n\n"
                "CUSTOMER REQUEST:\n"
                f"{compact_text(customer_request, 4500)}\n\n"
                f"PAGE {page_number} OF {total_pages}\n\n"
                "CURRENT PAGE:\n"
                f"{content}\n\n"
                "COMPLETE DOCUMENT CONTEXT:\n"
                f"{compact_text(complete_document, 8500)}\n\n"
                "Review this page intelligently.\n\n"
                "Check for genuine problems in:\n"
                "- correctness\n"
                "- completeness\n"
                "- relevance\n"
                "- grammar\n"
                "- clarity\n"
                "- consistency\n"
                "- structure\n"
                "- formatting\n"
                "- compliance with the customer's request\n\n"
                "Do not invent problems.\n"
                "Do not rewrite the page.\n"
                "Return review findings only."
            )

            review = self.call_groq(
                messages=[
                    {
                        "role":
                            "system",
                        "content":
                            system_prompt,
                    },
                    {
                        "role":
                            "user",
                        "content":
                            compact_text(
                                prompt,
                                REVIEW_REQUEST_CHARS,
                            ),
                    },
                ],
                output_tokens=REVIEW_OUTPUT_TOKENS,
                stage="DOCUMENT_REVIEW",
                event=event,
            )

            card = {
                "type":
                    "review_card",

                "page_number":
                    page_number,

                "position":
                    position,

                "total_pages":
                    total_pages,

                # COMPLETE ORIGINAL PAGE
                "content":
                    content,

                # REVIEW IS SEPARATE
                "review":
                    safe_text(review),

                "status":
                    "reviewed",
            }

            page_results.append(
                card
            )

            if progress_callback:

                progress_callback(
                    card
                )

        assembled_review = (
            self.assemble_review(
                page_results
            )
        )

        result = {
            "type":
                "review_completed",

            "status":
                "completed",

            "total_pages":
                total_pages,

            "pages":
                page_results,

            "assembled_review":
                assembled_review,
        }

        if progress_callback:

            progress_callback(
                result
            )

        return result

    # ========================================================
    # REVIEW ASSEMBLY
    # ========================================================

    @staticmethod
    def assemble_review(
        pages: list[
            dict[str, Any]
        ],
    ) -> str:

        ordered = sorted(
            pages,
            key=lambda item: int(
                item.get(
                    "page_number",
                    0,
                )
            ),
        )

        parts = []

        for page in ordered:

            review = safe_text(
                page.get(
                    "review"
                )
            )

            if not review:
                continue

            parts.append(
                "PAGE "
                + str(
                    page.get(
                        "page_number"
                    )
                )
                + "\n\n"
                + review
            )

        if not parts:

            return (
                "The complete document was reviewed "
                "and no review findings were returned."
            )

        return (
            "COMPLETE DOCUMENT REVIEW\n\n"
            + "\n\n".join(parts)
        )

    # ========================================================
    # CORRECTION
    # ========================================================

    def correct_document(
        self,
        *,
        document_pages: list[Any],
        correction: str,
        service: str | None,
        context: str | None,
        progress_callback: Callable[
            [dict[str, Any]],
            None
        ] | None = None,
    ) -> dict[str, Any]:
        """
        Correct the CURRENT document as one complete work.

        This intentionally avoids page-by-page independent
        rewriting.

        Ada sees the complete current document and the complete
        correction request.

        The resulting complete document is then paginated again.
        """

        pages = (
            self.normalize_document_pages(
                document_pages
            )
        )

        if not pages:

            raise AdaResponseError(
                "There is no document to correct.",
                stage="CORRECTION_INTAKE",
                category="EMPTY_DOCUMENT",
            )

        correction = safe_text(
            correction
        )

        if not correction:

            raise AdaResponseError(
                "Correction instruction is empty.",
                stage="CORRECTION_INTAKE",
                category="EMPTY_CORRECTION",
            )

        current_document = (
            self.assemble_document(
                pages
            )
        )

        active_service = (
            self.normalize_service(
                service
            )
            or safe_text(service)
            or self.service
            or "General Business Center Service"
        )

        system_prompt = (
            self.build_system_prompt(
                service=active_service,
                context=context,
            )
        )

        prompt = (
            "CURRENT DOCUMENT CORRECTION\n\n"
            f"SERVICE:\n{active_service}\n\n"
            "CUSTOMER'S CORRECTION:\n"
            f"{compact_text(correction, 6000)}\n\n"
            "CURRENT COMPLETE DOCUMENT:\n"
            f"{current_document}\n\n"
            "TASK\n"
            "====\n"
            "Apply the customer's correction to the CURRENT "
            "document.\n\n"
            "Return the COMPLETE corrected document.\n\n"
            "Do not return only the changed section.\n"
            "Do not return a summary.\n"
            "Do not return an explanation.\n"
            "Do not remove unrelated useful content.\n"
            "Do not revert to an older version.\n"
            "Do not invent customer facts.\n"
            "Preserve the document's useful structure.\n"
        )

        corrected = self.call_groq(
            messages=[
                {
                    "role":
                        "system",
                    "content":
                        system_prompt,
                },
                {
                    "role":
                        "user",
                    "content":
                        compact_text(
                            prompt,
                            CORRECTION_REQUEST_CHARS,
                        ),
                },
            ],
            output_tokens=CORRECTION_OUTPUT_TOKENS,
            stage="DOCUMENT_CORRECTION",
            event="document_correction",
        )

        corrected = safe_text(
            corrected
        )

        if not corrected:

            # Absolute safety:
            # never replace a document with empty content.
            corrected = current_document

        corrected_pages = (
            self.document_to_pages(
                corrected
            )
        )

        result = {
            "type":
                "correction_completed",

            "status":
                "completed",

            "total_pages":
                len(corrected_pages),

            "pages":
                corrected_pages,

            "document_text":
                corrected,
        }

        if progress_callback:

            progress_callback(
                result
            )

        return result

    # ========================================================
    # DOCUMENT ASSEMBLY
    # ========================================================

    @staticmethod
    def assemble_document(
        pages: list[
            dict[str, Any]
        ],
    ) -> str:

        ordered = sorted(
            pages,
            key=lambda item: int(
                item.get(
                    "page_number",
                    0,
                )
            ),
        )

        parts = []

        for page in ordered:

            content = safe_text(
                page.get(
                    "content"
                )
            )

            if content:
                parts.append(
                    content
                )

        return "\n\n".join(
            parts
        ).strip()

    # ========================================================
    # NORMAL CHAT
    # ========================================================

    def respond(
        self,
        message: str,
        service: str | None = None,
        event: str | None = None,
        context: str | None = None,
    ) -> str:

        message = safe_text(
            message
        )

        if not message:

            return (
                "Please tell me what you "
                "would like me to help you with."
            )

        if service:
            self.set_service(
                service
            )

        active_service = (
            self.normalize_service(
                self.service
            )
        )

        system_prompt = (
            self.build_system_prompt(
                service=active_service,
                context=context,
            )
        )

        messages = [
            {
                "role":
                    "system",
                "content":
                    system_prompt,
            }
        ]

        for item in self.history[
            -MAX_HISTORY_MESSAGES:
        ]:

            messages.append(
                {
                    "role":
                        item["role"],

                    "content":
                        compact_text(
                            item["content"],
                            MAX_HISTORY_MESSAGE_CHARS,
                        ),
                }
            )

        if event:

            messages.append(
                {
                    "role":
                        "system",

                    "content":
                        (
                            "CURRENT APPLICATION EVENT\n"
                            + safe_text(event)
                        ),
                }
            )

        messages.append(
            {
                "role":
                    "user",

                "content":
                    compact_text(
                        message,
                        MAX_USER_MESSAGE_CHARS,
                    ),
            }
        )

        response = self.call_groq(
            messages=messages,
            output_tokens=700,
            stage="NORMAL_RESPONSE",
            event=event,
        )

        self.add_history(
            "user",
            message,
        )

        self.add_history(
            "assistant",
            response,
        )

        return response

    # ========================================================
    # EVENT HELPERS
    # ========================================================

    @staticmethod
    def is_review_event(
        event: str | None,
    ) -> bool:

        return (
            safe_text(
                event
            ).lower()
            in REVIEW_EVENTS
        )

    @staticmethod
    def is_correction_event(
        event: str | None,
    ) -> bool:

        return (
            safe_text(
                event
            ).lower()
            in CORRECTION_EVENTS
        )


# ============================================================
# DIAGNOSTIC
# ============================================================

if __name__ == "__main__":

    print()
    print("=" * 78)
    print("NAIJA POCKET BUSINESS CENTER")
    print("ADA RESPONSE INTELLIGENCE ENGINE")
    print("=" * 78)

    print("Model:", MODEL)

    print(
        "Groq package:",
        "READY"
        if Groq is not None
        else "MISSING",
    )

    print(
        "API key:",
        "CONFIGURED"
        if API_KEY
        else "MISSING",
    )

    print(
        "Intelligence-first service requirements:",
        "ENABLED",
    )

    print(
        "Global page-count requirement:",
        "DISABLED",
    )

    print(
        "Complete document generation:",
        "ENABLED",
    )

    print(
        "Generation continuation:",
        "ENABLED",
    )

    print(
        "Document-to-page handoff:",
        "ENABLED",
    )

    print(
        "Original page preservation:",
        "ENABLED",
    )

    print(
        "Separate review findings:",
        "ENABLED",
    )

    print(
        "Complete-document correction:",
        "ENABLED",
    )

    print(
        "Keyword-only service logic:",
        "DISABLED",
    )

    print(
        "Permanent document ownership:",
        "APPLICATION",
    )

    print("=" * 78)
